### ISSUE TITLE
Python?

### ISSUE THREAD

**Issue by KeynesYouDigIt** [kwstat/agridat#15]
Sorry to just raise an issue here: Have y'all received interest in making this data easy to install and use with Python? I am an OSS contributor looking at https://github.com/Project-AgML/AgML and I am wondering if theres a chance to 

1) combine these fine data sets.

2) make them accessible in R and Python for ease of use.

I would still need to talk to the folks at AgML and make a plan, but would that be of interest to y'all?

**Comment by kwstat** [comment]
Thanks for telling me about AgML.  I will add a reference to it in my package documentation that links to other sources of agricultural data.

You are the first to mention python access to the data. I am not familiar with the python package system (other than knowing that it exists).

When I look at the AgML package, it seems to me that it fills a specific purpose in the Machine Learning world, whereas the agridat package is mostly focused on classical experimental designs. I'm not sure that it would really be beneficial to combine these two packages.
But, the agridat package has a permissive license and could be "re-mixed" for python (for example).

**Comment by adamhsparks** [comment]
This issue did make me think that it would be nice to port this to Julia where I think there would be good value with the classic experimental designs.
