### ISSUE TITLE
lsmeans is leaving

### ISSUE THREAD

**Issue by rvlenth** [kwstat/agridat#5]
Kevin,

I’m writing because your R package **agridat** still suggests the **lsmeans** package. For almost a year, the new package **emmeans** has been available, and I am planning to ask the CRAN team to deprecate it in the next few months. It is quite easy to make the transition to **emmeans**. There is a vignette providing some tips for how to do this at https://cran.r-project.org/web/packages/emmeans/vignettes/transition-from-lsmeans.html, and there is even a script for converting old R sources, vignettes, and workspaces.

Please let me know if you have any questions. I will keep in touch on this matter as is necessary.

Sincerely,

Russ Lenth

**Comment by kwstat** [comment]
Thanks. Fixed via https://github.com/kwstat/agridat/commit/2c1fac6da213b1a7cbc5a8da91f4e87ed1a053f8
