### ISSUE TITLE
3D yield response to fertilizers missing example

### ISSUE THREAD

**Issue by adamhsparks** [kwstat/agridat#6]
In the vignette the text states:

> The blue dots are observed data, and the tan surface is the fitted surface drawn by the rgl package).

However, there is no associated R code in the RMD file and `rgl` is not listed in the "Setup" section.

**Comment by kwstat** [comment]
Added this text:

Note: This image was created by manual manipulation of an `rgl` device.  The manual manipulation makes this non-reproducible in an `Rmd` file.  See the example for the `sinclair.clover` data for the code.

Is that sufficient?

**Comment by adamhsparks** [comment]
Makes sense to me and is more clear than it currently appeared.

Thanks!
