### ISSUE TITLE
ANOVA table for Alpha lattice design of spring oats, wrong d.f.

### ISSUE THREAD

**Issue by nandp1** [kwstat/agridat#9]
`anova(m1)`
Analysis of Variance Table

Response: yield
          Df  Sum Sq Mean Sq  F value    Pr(>F)    
**gen       24** 1458.83  60.785 728.2829 < 2.2e-16 ***
rep        2    6.14   3.068  36.7557 6.593e-09 ***
rep:block 15    3.60   0.240   2.8784  0.006255 ** 
Residuals 31    2.59   0.083   

**The degrees of freedom in the anova table for gen is 24 instead of 23, one less than number of levels. The df is wrong.** 

`str(dat)`
'data.frame':   72 obs. of  5 variables:
 $ plot : int  1 2 3 4 5 6 7 8 9 10 ...
 $ rep  : Factor w/ 3 levels "R1","R2","R3": 1 1 1 1 1 1 1 1 1 1 ...
 $ block: Factor w/ 6 levels "B1","B2","B3",..: 1 1 1 1 2 2 2 2 3 3 ...
 ** gen  : Factor w/ 24 levels **G01","G02","G03",..: 11 4 5 22 21 10 20 2 23 14 ...
 $ yield: num  4.12 4.45 5.88 4.58 4.65 ...
>

**Comment by kwstat** [comment]
Note, this is for the the `john.alpha` data.

The example code is this:
```
  # Block fixed (intra-block analysis) (bottom of table 7.4 in John)
  m1 <- lm(yield ~ 0 + gen + rep + rep:block, dat)
  anova(m1)
R>   anova(m1)
Analysis of Variance Table

Response: yield
          Df  Sum Sq Mean Sq  F value    Pr(>F)    
gen       24 1458.83  60.785 728.2829 < 2.2e-16 ***
rep        2    6.14   3.068  36.7557 6.593e-09 ***
rep:block 15    3.60   0.240   2.8784  0.006255 ** 
Residuals 31    2.59   0.083                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

```

The reason the d.f. for `gen` is 24 is because the model does not have an intercept.  `yield~-1` and `yield~0` are two ways to remove the intercept from the model.  If you allow an intercept in the model, then the d.f. for `gen` will be 23:
```
R> anova(lm(yield ~ gen + rep + rep:block, dat))
Analysis of Variance Table

Response: yield
          Df  Sum Sq Mean Sq F value    Pr(>F)    
gen       23 14.0765 0.61202  7.3329 3.632e-07 ***
rep        2  6.1355 3.06774 36.7557 6.593e-09 ***
rep:block 15  3.6036 0.24024  2.8784  0.006255 ** 
Residuals 31  2.5874 0.08346                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```
